
spring:
  application:
    name: "BankAPI"
  datasource:
    driver:
      class:
    driver-class-name:
    url: jdbc:h2:mem:BankDB;MODE=PostgreSQL
    username: BANK_USER
    password: BANK_PASSWORD
    hikari:
      maximum-pool-size: 100
      minimum-idle: 4
      connection-timeout: 90000
      leak-detection-threshold: 10000
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

banking:
  client:
    base-url: https://sandbox.platfr.io
    auth-schema: S2S
    api-key: ${FABRICK_API_KEY:test}

logging:
  pattern:
    level: "%4p [%X{traceId:-}]"